name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allow running manually from Actions tab
  workflow_dispatch:

jobs:
  shellcheck:
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: ShellCheck
        uses: ludeeus/action-shellcheck@master
        env:
          SHELLCHECK_OPTS: -s bash -e SC2119 -e SC2120
          # SC2119 - our functions' $1 is never script's $1
          # SC2120 - our functions, by nature, define arguments we won't use within basherk
